plugins {
    id "java"
    id "application"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "com.example.virtualthreadsdemo.VirtualThreadsTask"
}

repositories {
    mavenCentral()
}