spring.application.name=application
spring.config.import=kubernetes:
spring.cloud.kubernetes.client.namespace=${POD_NAMESPACE:default}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.cloud.kubernetes.config.enabled=true

spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.reload.mode=event
spring.cloud.kubernetes.reload.strategy=refresh
spring.cloud.kubernetes.reload.monitor-config-maps=true
